os: osx

language: node_js
node_js:
  - 10 # use nodejs v10 LTS

cache: npm

branches:
  only:
    - manuscript # build manuscript branch only

script:
  - npm install hexo-cli -g
  - npm install
  - hexo version # check hexo version
  - hexo clean
  - hexo generate # generate static files

before_deploy:
  - cp CNAME public # copy CNAME for custom domain

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  on:
    branch: manuscript
  local_dir: public
  target_branch: master
  keep_history: false
  verbose: true
